spring:
  application:
    name: gateway-service

  cloud:
    config.uri: http://localhost:8888
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        ## company-service
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/company/**
          filters:
            - StripPrefix=1
        ## user-service
        - id: user-service
          uri: lb://user-service
          ## @RequestMapping
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} -%msg%n"