-- liquibase formatted sql

-- changeset alexey:1-create-sequence-user_ds_seq
CREATE SEQUENCE  IF NOT EXISTS user_ds_seq START WITH 1 INCREMENT BY 50;

-- changeset alexey:2-create-table-user_ds
CREATE TABLE user_ds (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, company_id BIGINT, email VARCHAR(255), enabled BOOLEAN NOT NULL, login VARCHAR(255), name VARCHAR(255), password VARCHAR(255), CONSTRAINT "user_dsPK" PRIMARY KEY (id));

