server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} -%msg%n"

spring:
  cloud:
    gateway:
      routes:
        ## user-service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
        ## company-service
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/company-service/**
          filters:
            - StripPrefix=1